export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_PROGRESS = "LOGIN_PROGRESS";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
export const LOGOUT_PROGRESS = "LOGOUT_PROGRESS";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const SIGNUP_PROGRESS = "SIGNUP_PROGRESS";

export const FETCH_CARDS_SUCCESS = "FETCH_CARDS_SUCCESS";
export const FETCH_CARDS_FAILED = "FETCH_CARDS_FAILED";
export const FETCH_CARDS_PROGRESS = "FETCH_CARDS_PROGRESS";

export const ADD_CARD_SUCCESS = "ADD_CARD_SUCCESS";
export const ADD_CARD_FAILED = "ADD_CARD_FAILED";
export const ADD_CARD_PROGRESS = "ADD_CARD_PROGRESS";