export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_PROGRESS = "LOGIN_PROGRESS";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const SIGNUP_PROGRESS = "SIGNUP_PROGRESS";

export const FETCH_CARDS_SUCCESS = "FETCH_CARDS_SUCCESS";
export const FETCH_CARDS_FAILED = "FETCH_CARDS_FAILED";
export const FETCH_CARDS_PROGRESS = "FETCH_CARDS_PROGRESS";